project:
  type: book
  output-dir: _book

book:
  title: "Yaşam Bilimlerinde Veri Analizi"
  author: "Emrah Kırdök, Ph.D."
  date: "2023/02/23"
  favicon: "images/ybva.png"
  reader-mode: true

  sidebar:
    logo: "images/ybva.png"

  page-footer:
    left: |
      Yaşam Bilimlerinde Veri Analizi
      Emrah Kırdök, Ph.D.
    right: |
      Bu kitap Veri Analizi, İstatistiksel Öğrenme, ve
      Yaşam Bilimlerinde Veri Analizi Dersleri için
      kaynak olarak kullanılacaktır.
  site-url: https://emrahkirdok.github.io/ybva/
  repo-url: https://github.com/emrahkirdok/ybva/
  
  chapters:
    - index.qmd
    - CONTRIBUTING.md
    
    - part: "Derse Hazırlık"
      chapters:
        - 01-kurulum/01-r-rstudio-kurulum.qmd
        - 01-kurulum/02-ilk-kurallar.qmd
        - 01-kurulum/03-r-rstudio-ilk-adimlar.qmd
        - 01-kurulum/04-klasor-islemleri.qmd

    - part: "Veri Analizi"
      chapters:
        - 02-veri-analizi/01-veri-bilimine-giris.qmd
        - 02-veri-analizi/02-bilimsel-yontem.qmd
        - 02-veri-analizi/03-r-giris.qmd
        - 02-veri-analizi/04-vektorler.qmd
#        - 02-veri-analizi/05-matrisler.qmd
#        - 02-veri-analizi/06-Rmarkdown.qmd
#        - 02-veri-analizi/07-veri-cerceveleri.qmd
#        - 02-veri-analizi/08-tibble.qmd
#        - 02-veri-analizi/09-listeler.qmd
#        - 02-veri-analizi/10-veri-cercevesi-vs-tibble.qmd
#        - 02-veri-analizi/11-veri-islemleri.qmd
#        - metin_bilimsel_hikaye_anlaticiligi.Rmd
#        - metin_rmarkdown_odevleri_bilgi.Rmd
#        - metin_dogrusal_modelleme_uygulamasi_1.Rmd
#        - metin_ggplot2_grafik_dilbilgisi.Rmd
#        - metin_lojistik_regresyon.Rmd
#        - metin_t_test.Rmd
#
    - part: "Bilgisayarlı Düşünme"
#      chapters:
         - 03-bilgisayarli-dusunme/01-ileri-seviye-r-01.qmd
#        - metin_asamali_azalis.Rmd
#        - metin_amphiBIO_calisma.Rmd
    
    - part: "Uygulamalar"
#      chapters:
#        - metin_03_pratik.Rmd
#        - metin_03_vektorler_pratik.Rmd
#        - metin_04_pratik.Rmd
#        - metin_ggplot2_pratik.Rmd
    
    - part: "Türkiye'nin Verisi"
  
    - references.qmd

  appendices:
    - 10-ekler/01-sunumlar.qmd


bibliography : bibliography.bib
lang: tr

language:
  tr:
    crossref-fig-title: "Şekil"

format:
  html:
    mainfont: helvetica
    theme:
      - darkly
    code-link: true
  pdf:
    documentclass: scrbook
    author-meta: "Emrah Kırdök"
